### ISSUE TITLE
Update node-sass and sass-loader

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#836]

**Comment by inghylt** [comment]
Non functional website but running container with this error message

./src/App.vue?vue&type=style&index=0&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/project/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/project/node_modules/sass-loader/dist/index.js:79:18)
    
    
```
ma-exec frontend node --version
v16.13.2

ma-exec frontend cat package.json
{
  "name": "metabolic_atlas_frontend",
  "version": "1.0.0",
  "description": "Metabolic Atlas",
  "author": "https://nbis.se",
  "license": "GPL-3.0-only",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --mode local",
    "build": "vue-cli-service build --mode production",
    "lint": "eslint src --ext .js,.vue",
    "check-format": "prettier -l src",
    "format": "prettier -w src"
  },
  "dependencies": {
    "@metabolicatlas/3d-network-viewer": "^0.1.18",
    "@panzoom/panzoom": "^4.4.3",
    "axios": "^0.24.0",
    "bulma": "^0.9.0",
    "bulma-timeline": "^3.0.4",
    "cytoscape": "3.2.9",
    "cytoscape-cola": "2.5.0",
    "eslint-config-prettier": "^8.3.0",
    "file-saver": "^2.0.2",
    "jquery": "3.6.0",
    "nprogress": "0.2.0",
    "vue": "^2.6.10",
    "vue-color": "2.8.1",
    "vue-cookie": "^1.1.4",
    "vue-debounce": "^3.0.2",
    "vue-good-table": "^2.21.11",
    "vue-lodash": "^2.1.2",
    "vue-matomo": "^4.1.0",
    "vue-meta": "^2.4.0",
    "vue-router": "^3.5.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.15",
    "@vue/cli-plugin-eslint": "^4.5.15",
    "@vue/cli-service": "^4.5.15",
    "@vue/eslint-config-airbnb": "^5.3.0",
    "babel-eslint": "^10.0.1",
    "compression-webpack-plugin": "^6.1.1",
    "eslint": "^6.5.1",
    "eslint-plugin-vue": "^8.3.0",
    "node-sass": "^6.0.0",
    "prettier": "^2.5.1",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-webpack-bundle-analyzer": "^4.0.0",
    "vue-template-compiler": "^2.6.10"
  }
}
```

**Comment by inghylt** [comment]
node:17 with 

 ```
 "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.15",
    "@vue/cli-plugin-eslint": "^4.5.15",
    "@vue/cli-service": "^4.5.15",
    "@vue/eslint-config-airbnb": "^5.3.0",
    "babel-eslint": "^10.0.1",
    "compression-webpack-plugin": "^6.1.1",
    "eslint": "^6.5.1",
    "eslint-plugin-vue": "^8.3.0",
    "node-sass": "^7.0.1",
    "prettier": "^2.5.1",
    "sass-loader": "^12.0.0",
    "vue-cli-plugin-webpack-bundle-analyzer": "^4.0.0",
    "vue-template-compiler": "^2.6.10"
  }
}
```

leads to broken frontend container

logs frontend showed

```


frontend  | Error: error:0308010C:digital envelope routines::unsupported
frontend  |     at new Hash (node:internal/crypto/hash:67:19)
frontend  |     at Object.createHash (node:crypto:130:10)
frontend  |     at module.exports (/project/node_modules/webpack/lib/util/createHash.js:135:53)
frontend  |     at NormalModule._initBuildHash (/project/node_modules/webpack/lib/NormalModule.js:417:16)
frontend  |     at handleParseError (/project/node_modules/webpack/lib/NormalModule.js:471:10)
frontend  |     at /project/node_modules/webpack/lib/NormalModule.js:503:5
frontend  |     at /project/node_modules/webpack/lib/NormalModule.js:358:12
frontend  |     at /project/node_modules/loader-runner/lib/LoaderRunner.js:373:3
frontend  |     at iterateNormalLoaders (/project/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
frontend  |     at iterateNormalLoaders (/project/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
frontend  |     at /project/node_modules/loader-runner/lib/LoaderRunner.js:236:3
frontend  |     at runSyncOrAsync (/project/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
frontend  |     at iterateNormalLoaders (/project/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
frontend  |     at Array.<anonymous> (/project/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
frontend  |     at Storage.finished (/project/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
frontend  |     at /project/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
frontend  | node:internal/crypto/hash:67
frontend  |   this[kHandle] = new _Hash(algorithm, xofLen);
frontend  |                   ^
frontend  | 
frontend  | Error: error:0308010C:digital envelope routines::unsupported
frontend  |     at new Hash (node:internal/crypto/hash:67:19)
frontend  |     at Object.createHash (node:crypto:130:10)
frontend  |     at module.exports (/project/node_modules/webpack/lib/util/createHash.js:135:53)
frontend  |     at NormalModule._initBuildHash (/project/node_modules/webpack/lib/NormalModule.js:417:16)
frontend  |     at handleParseError (/project/node_modules/webpack/lib/NormalModule.js:471:10)
frontend  |     at /project/node_modules/webpack/lib/NormalModule.js:503:5
frontend  |     at /project/node_modules/webpack/lib/NormalModule.js:358:12
frontend  |     at /project/node_modules/loader-runner/lib/LoaderRunner.js:373:3
frontend  |     at iterateNormalLoaders (/project/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
frontend  |     at Array.<anonymous> (/project/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
frontend  |     at Storage.finished (/project/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
frontend  |     at /project/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
frontend  |     at /project/node_modules/graceful-fs/graceful-fs.js:123:16
frontend  |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
frontend  |   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
frontend  |   library: 'digital envelope routines',
frontend  |   reason: 'unsupported',
frontend  |   code: 'ERR_OSSL_EVP_UNSUPPORTED'
frontend  | }
frontend  | 
frontend  | Node.js v17.3.1
frontend  | error Command failed with exit code 1.
frontend  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

**Comment by inghylt** [comment]
https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

Based on this thread to solve the issue above, `ENV NODE_OPTIONS=--openssl-legacy-provider ` was added to line 5 in frontend/Dockerfile

**Comment by inghylt** [comment]
https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function

Then we tried downgrading sass-loader to ` "sass-loader": "^10.0.0",` as suggested in the thread above, both with node 16/and node-sass 6.0.0 and 17/7.0.0. It did not fix the problem, but a new error occurred in the frontend

```
./src/App.vue?vue&type=style&index=0&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'data'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
    at validate (/project/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.loader (/project/node_modules/sass-loader/dist/index.js:30:29)
```

**Comment by inghylt** [comment]
It might be that we need to do something with webpack, or something else that we have not yet discovered

**Comment by mihai-sysbio** [comment]
After noticing that `node-sass` is deprecated, switching to the latest version of `sass` went smoothly.
I have verified that the incompatibility arises between `vue-style-loader` and `sass-loader` exactly like in @inghylt's post above. It seems that simply renaming `data` to `additionalData` inside `vue.config.js` does the trick. You can try this out in the branch [`fix/node-sass`](https://github.com/MetabolicAtlas/MetabolicAtlas/compare/fix/update-dependencies...fix/node-sass?expand=1), which is based on `fix/update-dependencies` and `fix/build-script`. All the new changes are in commit c2f7f724bb3290ad33c5cd912b1da3f502ae937b. If it looks look, please cherry-pick or create a PR as you see fit.
